{
  "hash": "0336f9c7887d654d194b12560cd9e5d6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework5\"\nauthor: \"Katie Park\"\ndate: \"2024-10-9\"\nformat:\n  html: default\n  pdf: default\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nwdi <- read.csv(\"wdi.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(wdi$gdp_per_capita)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n    259    2571    7588   20346   25983  240862      14 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(wdi$primary_school_enrolment_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  64.40   94.19  100.02  100.87  105.04  138.19     103 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(wdi$adult_literacy_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  27.28   72.40   83.78   79.57   95.50  100.00     168 \n```\n\n\n:::\n:::\n\n\n\n\n# Summary gdp_per_capita\nThe summary of gdp_per_capita shows that the lowest GDP per capita for a country is $259, which suggests that the country has low economic output per person. The median of the countries is 7588 which shows the middle value of all the countires. The mean is 20346 which suggest that there are many countries with low GDP per capita, but some countries have very high GDP which scews the mean to a high value.\n\n# Summary primary_school_enrolment_rate\nThe summary of primary school enrollment rate shows that the minimum enrollment rate is 64.4% which means a country has only 64.4% of primary aged people enrolled in school. The median is 100.02 and the mean is 100.87 which are relative similar which suggests that most countries have all of their primary aged people enrolled in school. The maximum is 138.19 which suggests over-enrolledment in schools.  \n\n# Summary adult literacy rate\nThe summary of gdp adult literacy rate shows that the minimum adult literacy rate is 27.28% which shows that some countires have very low literacy levels among adults. The median is 83.78 which shows that half of the countries in the data set have a literacy rate above and below this level. The mean is 79.57 and is lower than the median which suggests that there a more countires with lower literacy rates. \n\n# Adult Literacy Rates by Country (Table 1)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Homework5_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n[Data source, click here](wdi.csv)\n\n# GDP Per Capita By Country (Table 2)\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Homework5_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n[Data source, click here](wdi.csv)\n\n# GDP Per Capita and Adult Literacy Rate (Table 3)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Homework5_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n[Data source, click here](wdi.csv)\n\n# Primary School Enrollment and Adult Literacy Rate (Table 4)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Homework5_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n[Data source, click here](wdi.csv)\n\n| Key statistics|\n|----------|\n| Table 3 shows that Countries that had high GDP per capital, tend to have have higer adult literacy rates than lower GPD per capital counties|\n|Table 1 and 2 shows that countries that had recorded GDP per captia and adult literacy rates are mostly non-western countries.|\n|Table 4 shows that higher primary school enrollment rates tened to have higher adult literacy rates|\n|Table 4 shows that over 100% primary school enrollment rates led to lower adult literacy rates|\n\n@article\nhttps://ourworldindata.org/grapher/literacy-rate-vs-gdp-per-capita\n\n@article{LiteracyRatevsGDPperCaptia,\n  title={Literacy rate vs. GDP per capita, 2023},\n  author={Our world in Data},\n  year={2023},\n  url={https://ourworldindata.org/grapher/literacy-rate-vs-gdp-per-capita},\n  publisher={Our world in Data}\n}\n\n@article{relationshipbtwenEcnomicAndSchool,\n  title={The Relationship between Economic Growth and School Enrollment Rates: Time Series\nEvidence from Turkey},\n  aurthor={Sedat Gumus, Selim Kayhan}\n  year={2012},\n  url={https://files.eric.ed.gov/fulltext/EJ1127574.pdf},\n  publisher={Inased}\n}",
    "supporting": [
      "Homework5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}